moviedb/movie_data/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    url('movies', views.movielist, name="movielist"),
    url(r'^movie/(?P<id>[0-9]+)/$', views.moviepage, name="moviepage"),
    url('artists', views.artistlist, name="artistlist"),
    url(r'^artist/(?P<id>[0-9]+)/$', views.artistpage, name="artistpage"),
]

moviedb/moviedb/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html')),
    url('', include('movie_data.urls'))
]
1

moviedb/movie_data/models.py
from django.db import models
from django.contrib import admin
from django.utils import timezone

class artist(models.Model):
    name = models.CharField(max_length=200, verbose_name='ARTIST')
    imdb_id = models.CharField(max_length=30, verbose_name='IMDB ID')

    class meta:
        verbose_name = "Artist"
        verbose_name_plural = "Artists"

    def __str__(self):
        return self.name

class movie(models.Model):
    imdb_id = models.CharField(max_length=30,verbose_name='IMDB ID')
    title = models.CharField(max_length=100,verbose_name='MOVIE NAME')
    director = models.ForeignKey(artist, on_delete=models.CASCADE, verbose_name='DIRECTOR')
    artists = models.ManyToManyField(artist, related_name = 'actor', through='roles', verbose_name='ACTORS/ACTRESS IN THIS MOVIE')

    class meta:
        verbose_name = "Movie"
        verbose_name_plural = "Movies"

    def __str__(self):
        return self.title

class roles(models.Model):
    role_name = models.CharField(max_length=100,verbose_name='ROLE OF ACTOR IN MOVIE')
    artist = models.ForeignKey(artist, on_delete=models.CASCADE, verbose_name='SELECT ARTIST PROFILE')
    movie = models.ForeignKey(movie, on_delete=models.CASCADE, verbose_name='SELECT MOVIE PROFILE')

    class meta:
        verbose_name = "Role"
        verbose_name_plural = "Roles"

    def __str__(self):
        return self.role_name

class roles_inline(admin.TabularInline):
    model = roles
    extra = 1

class artistAdmin(admin.ModelAdmin):
    inlines = (roles_inline,)

class movieAdmin(admin.ModelAdmin):
    inlines = (roles_inline,)

moviedb/movie_data/views.py
from django.shortcuts import render
from . import models

def moviepage(request,id):
    movie = models.movie.objects.get(pk=id)
    return render(request, 'movie/single.html',{'movie':movie})

def movielist(request):
     movies = models.movie.objects.all()
     return render(request, 'movie/list.html', {'movies': movies})

def artistpage(request,id):
    artist = models.artist.objects.get(pk=id)
    return render(request, 'artist/single.html',{'artist':artist})

def artistlist(request):
     artists = models.artist.objects.all()
     return render(request, 'artist/list.html', {'artists': artists})

moviedb/movie_data/templates/artist/list.html
{% extends 'base.html' %}
{% block title %}Artist List{% endblock %}
{% block content %}

<h1>Artist List</h1>
<div class="row m-0">
{% for artist in artists %}
  <div class="col-md-4">
    <div class="card">
        <div class="card-body">
          <h4 class="card-title">{{artist.name}}</h4>
          <a href="/artist/{{artist.id}}/" class="btn btn-primary">View</a>
        </div>
      </div>
    </div>
{% endfor %}
</div>

{% endblock %}

moviedb/movie_data/templates/artist/single.html
{% extends 'base.html' %}
{% block title %}{{ artist.name }} | Artist Profile {% endblock %}
{% block content %}

<h1>{{ artist.name }}</h1>
<b>Imdb ID:</b> {{ artist.imdb_id }}

<div class="py-2">
  <h3 class="m-0">Movies</h3>
  <div class="row m-0">
  {% for movie in artist.roles_set.all %}
    <div class="col-md-3 col-sm-6 p-2">
      <div class="card p-2">
        <h2 class="m-0"> {{movie.movie.title}} </h2>
        <div class="font-weight-bold"> {{movie.role_name}} </div>
        <a href="/movie/{{movie.movie.id}}/" class="btn btn-primary">View</a>
      </div>
    </div
  {% endfor %}
  </div>
</div>

{% endblock %}

moviedb/movie_data/templates/base.html
<!DOCTYPE html>
<html>
<head>

  <title>{% block title %}{% endblock %} | Movie DB</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">

</head>
<body>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="row m-0 w-100">
      <div class="col-sm-3">
        <a href="/" style="text-decoration: none;"><div class="text-light h3 m-2 font-weight-bold">MovieDb</div></a>
      </div>
      <div class="col">
        <ul class="navbar-nav p-1 font-weight-bold">
          <li class="nav-item">
            <a class="nav-link" href="/movies/">Movies</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/artists/">Artists</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container p-2">
  {% block content %}
  {% endblock %}
  </div>

</body>
</html>

moviedb/movie_data/templates/home.html
{% extends 'base.html' %}
{% block title %}Home Page{% endblock %}
{% block content %}
<div class="container">
  <h1>MovieDB</h1>
  <h4> MovieDB  is a simple API-based applicaion that manages movie and artist details.</h4>
</div>
{% endblock %}

moviedb/movie_data/templates/movie/list.html
{% extends 'base.html' %}
{% block title %}Movie List{% endblock %}
{% block content %}

<h1>Movie List</h1>
<div class="row m-0">
{% for movie in movies %}
  <div class="col-md-4">
    <div class="card">
        <div class="card-body">
          <h4 class="card-title">{{movie.title}}</h4>
          <a href="/movie/{{movie.id}}/" class="btn btn-primary">View</a>
        </div>
      </div>
    </div>
{% endfor %}
</div>

{% endblock %}

moviedb/movie_data/templates/movie/single.html
{% extends 'base.html' %}
{% block title %}{{ movie.title }} | Movie Profile {% endblock %}
{% block content %}

<h1>{{ movie.title }}</h1>
<div><b>Director:</b> {{ movie.director.name }}</div>
<div><b>Imdb ID:</b> {{ movie.imdb_id }}</div>

<div class="py-2">
  <h3 class="m-0">Artists</h3>
  <div class="row m-0">
  {% for artist in movie.roles_set.all %}
    <div class="col-md-3 col-sm-6 p-2">
      <div class="card p-2">
        <h2 class="m-0"> {{artist.artist.name}} </h2>
        <div class="font-weight-bold"> {{artist.role_name}} </div>
        <a href="/artist/{{artist.artist.id}}/" class="btn btn-primary">View</a>
      </div>
    </div
  {% endfor %}
  </div>
</div>

{% endblock %}